### ISSUE TITLE
percentageOfSecondRank attribute is null

### ISSUE THREAD

**Issue by sandroacoelho** [dbpedia-spotlight/dbpedia-spotlight-services#4]
@andyfaizan 

2.) The new api i.e. http://api.dbpedia-spotlight.org/annotate/ returns null for the percentageOfSecondRank attribute. Is this a known issue?

**Comment by andyfaizan** [comment]
Also, it has a typo - its "percentageOfSecondRan". No 'k' at the end.

**Comment by sandroacoelho** [comment]
Hi @andyfaizan,

It's fixed. Could you please test it?

Thanks

**Comment by andyfaizan** [comment]
@sandroacoelho Many thanks. It works now! :)
